Enh ssl
OctopusDeploy/OctopusDSC pull request #263
Opened 2020-11-04 00:17 UTC by twerthi

Adding ability to use an existing SSL certificate during configuration and create the SSL binding.

2020-11-04 00:39 UTC, matt-richardson requested changes
Looks like a good start. As mentioned in slack, I'm somewhat hesitant on this (though I'm not saying no to it) as while adding this makes some situations easier, it also makes the DSC more complicated to use and maintain. 

I'm wondering if we could rely on something in the readme (saying how to use a script task / third party DSC resource)? 

Or even, what if we made this change a cOctopusSslCertificate resource of its own? That might be nicest? That will make it nice and self contained from both a maintenance and a usage basis?

I'd definitely like to see some tests around this too.

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +        [string]$SSLWebListenPrefix = [string]::Empty
This shouldn't be here. It's just part of `WebListenPrefix`

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +                $existingSSLConfig = (Get-CurrentSSLBinding -ApplicationId "{E2096A4C-2391-4BE1-9F17-E353F930E7F1}")
A comment (with a link) of what this guid links to would be good

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +
```suggestion
```

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +    if (($SSLPort -ne 443) -and (!$SSLWebListenPrefix.Contains(":$SSLPort")))
Change this to compare against `WebListenPrefix` instead

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +    if (![string]::IsNullOrEmpty($SSLCertificateThumbprint) -and ![string]::IsNullOrEmpty($SSLCertificateStoreName))
This should be checking if the values have changed, otherwise it will be slow as it's resetting values that haven't changed.

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +        $args = @(
This will bounce the server every time DSC runs

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +    if (![string]::IsNullOrEmpty($SSLCertificateThumbprint) -and ![string]::IsNullOrEmpty($SSLCertificateStoreName))
This is in the wrong spot - we should be doing this up above before we restart the service.
We dont want to stop/start the service multiple times.
This is also pretty identical to the other code - )if it remains identical) it should move to a function

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +Write-Verbose "Testing key $key"
This function should be generic - it shouldn't have custom code in it.
It looks like if you drop `SSLWebListenPrefix` and just use `WebListenPrefix`, it should drop the need for this code

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +
```suggestion
```

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +
```suggestion
```

2020-11-04 00:39 UTC, matt-richardson commented on OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1
> +    $certificateBindings = (& netsh http show sslcert) | select-object -skip 3 | out-string
Is there any built in powershell commands to do this? This feels fragile.

2020-12-10 11:22 UTC, BenAkor commented
> Looks like a good start. As mentioned in slack, I'm somewhat hesitant on this (though I'm not saying no to it) as while adding this makes some situations easier, it also makes the DSC more complicated to use and maintain.
> 
> I'm wondering if we could rely on something in the readme (saying how to use a script task / third party DSC resource)?
> 
> Or even, what if we made this change a cOctopusSslCertificate resource of its own? That might be nicest? That will make it nice and self contained from both a maintenance and a usage basis?
> 
> I'd definitely like to see some tests around this too.

If this will be difficult to maintain. Could the ForceSSL be adjusted to nullable bool as the AutologinEnabled is set.

2020-12-11 01:13 UTC, matt-richardson commented
> If this will be difficult to maintain. Could the ForceSSL be adjusted to nullable bool as the AutologinEnabled is set?

I'm not sure I follow, @BenAkor. I'm not sure how ForceSSL & AutoLoginEnabled related to this PR? Can you expand?

2020-12-12 15:13 UTC, BenAkor commented
> > If this will be difficult to maintain. Could the ForceSSL be adjusted to nullable bool as the AutologinEnabled is set?
> 
> I'm not sure I follow, @BenAkor. I'm not sure how ForceSSL & AutoLoginEnabled related to this PR? Can you expand?

I initiated the need for the Octopus Server DSC resource to install and bind certificate (self-signed or other) in this [support forum](https://help.octopus.com/t/octopus-server-dsc-https-config-need-certificate-or-certificate-config-property/25852/2) post. At this time we have a work around to do that. But since the ForceSSL is set to False by default we will always have ForceSSL set to False and then back to True on every run which seems unacceptable for desired state. So by setting a nullable bool on the ForceSSL then it could be set to null by default instead of False. In that case it will not be setting force ssl to false and then to true on every run. Since the ForceSSL needs a certificate bound when set to true and Octopus Server DSC resource does not have bind certificate, the ForceSSL can only be used after the DSC resource runs. Hope this gives you some idea here.

2020-12-21 03:23 UTC, matt-richardson commented
> > > If this will be difficult to maintain. Could the ForceSSL be adjusted to nullable bool as the AutologinEnabled is set?
> > 
> > 
> > I'm not sure I follow, @BenAkor. I'm not sure how ForceSSL & AutoLoginEnabled related to this PR? Can you expand?
> 
> I initiated the need for the Octopus Server DSC resource to install and bind certificate (self-signed or other) in this [support forum](https://help.octopus.com/t/octopus-server-dsc-https-config-need-certificate-or-certificate-config-property/25852/2) post. At this time we have a work around to do that. But since the ForceSSL is set to False by default we will always have ForceSSL set to False and then back to True on every run which seems unacceptable for desired state. So by setting a nullable bool on the ForceSSL then it could be set to null by default instead of False. In that case it will not be setting force ssl to false and then to true on every run. Since the ForceSSL needs a certificate bound when set to true and Octopus Server DSC resource does not have bind certificate, the ForceSSL can only be used after the DSC resource runs. Hope this gives you some idea here.

I don't think I'm clear on why ForceSSL needs to be set to false? What is stopping you from setting it to true? What error messages are you seeing? 

> Since the ForceSSL needs a certificate bound when set to true
I'm really not clear here. It doesn't need a certificate bound?

Looking forward to getting to the bottom of this.

While we're digging into this, did you want to take a look at https://github.com/OctopusDeploy/OctopusDSC/pull/265? This is a bit of a spike to implement the nullable bool as you've requested. Would that work for your scenario?

2021-01-06 22:46 UTC, twerthi commented
Closing this PR as the SSL functionality has been moved to a new DSC resource instead of being included in OctopusServer.  Refer to https://github.com/OctopusDeploy/OctopusDSC/pull/267 for the new resource.

2021-01-06 22:46 UTC, closed without merging